$schema: https://raw.githubusercontent.com/streetsidesoftware/cspell/main/cspell.schema.json
version: "0.2"
ignorePaths:
  - "coverage/**"
  - "*.txt" # ignore text files at the root of the project
words:
  - spacetraders
  - newtype
  - newtypes
  - eseidel
  - cooldown
  - petstore
  - parseable
  - unparseable
  - renderable
  - Seidel
  - mocktail
  - pubspec
  - dartdoc
  - uncompilable
  - endtemplate
  - codepush
  - octocat
  - regen
  - dispatchable
  - unioned
  - watchcrunch
  - dedup
  - enumless
  - worktree
  - worktrees
  - smoosh
  - smooshing
  - isinstance
  - elif
