$schema: https://raw.githubusercontent.com/streetsidesoftware/cspell/main/cspell.schema.json
version: "0.2"
ignorePaths:
  - "coverage/**"
  - "*.txt" # ignore text files at the root of the project
words:
  - spacetraders
  - newtype
  - eseidel
  - cooldown
  - petstore
  - parseable
  - Seidel
  - mocktail
  - pubspec
