name: space_gen
description: An OpenAPI generator, focused on generating high quality code.
version: 1.0.0
repository: https://github.com/eseidel/space_gen

environment:
  sdk: ^3.8.0

dependencies:
  args: ^2.4.2
  collection: ^1.19.1
  equatable: ^2.0.7
  file: ^7.0.0
  http: ^1.4.0
  mason_logger: ^0.3.3
  meta: ^1.10.0
  mustache_template: ^2.0.0
  path: ^1.8.3
  scoped_deps: ^0.1.0+2
  version: ^3.0.2
  yaml: ^3.1.3

dev_dependencies:
  lints: ^6.0.0
  mocktail: ^1.0.4
  test: ^1.21.0
  very_good_analysis: ^9.0.0
