name: coverage

on:
  check_run:
    types: [completed]

permissions:
  id-token: write

jobs:
  upload:
    runs-on: ubuntu-latest
    if: ${{ github.event.check_run.name == 'Detect Changes' }}
    steps:
      - run: echo ${{ github.event.check_run.name }}